### ISSUE TITLE
Release v0.8

### ISSUE THREAD

**Issue by bvssvni** [PistonDevelopers/dyon#269]
This is a tracking issue for the next release of Dyon.

- [x] Land secrets PR https://github.com/PistonDevelopers/dyon/pull/268
- [x] Add missing features to README
- [x] Write blog with summary of new features
- [x] Demonstrate Dyon in Asteroids demo with Piston/Glium 2D + 3D + sound https://github.com/PistonDevelopers/dyon/issues/145
- [x] Improve type checker for missing spots
- [x] Add lazy boolean expressions https://github.com/PistonDevelopers/dyon/issues/251
- [x] Use hidden dynamic scope for current objects https://github.com/PistonDevelopers/dyon/issues/238
